root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -ldflags=-H=windowsgui -o tmp/main.exe ."
  bin = "tmp/main.exe"
  delay = 200
  exclude_dir = ["tmp", "vendor"]
  include_ext = ["go", "tpl", "tmpl", "html"]

[misc]
  hide_executable_console = true

[screen]
  clear_on_rebuild = true
